# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gdata-api}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fedor Kocherga"]
  s.date = %q{2010-02-02}
  s.email = %q{fkocherga@gmail.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "gdata-api.gemspec",
     "gdata_samples/calendar_data.xml",
     "gdata_samples/id_self_edit_links",
     "lib/gdata/atom.rb",
     "lib/gdata/base.rb",
     "lib/gdata/cacher.rb",
     "lib/gdata/calendar.rb",
     "lib/gdata/contacts.rb",
     "lib/gdata/data.rb",
     "lib/gdata/request.rb",
     "lib/gdata/uriutils.rb",
     "mongo_test.rb",
     "test/calendar_test.rb",
     "test/contacts_test.rb",
     "test/contacts_unit_test.rb",
     "test/data_xml_test.rb",
     "test/test_helper.rb",
     "todo.txt"
  ]
  s.homepage = %q{http://github.com/fkocherga/gdata-api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Google Data API expressed in Ruby}
  s.test_files = [
    "test/calendar_test.rb",
     "test/contacts_test.rb",
     "test/contacts_unit_test.rb",
     "test/data_xml_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<blankslate>, [">= 2.1.2.2"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_runtime_dependency(%q<tagged_logger>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<redis>, [">= 0"])
    else
      s.add_dependency(%q<blankslate>, [">= 2.1.2.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_dependency(%q<tagged_logger>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 0"])
    end
  else
    s.add_dependency(%q<blankslate>, [">= 2.1.2.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    s.add_dependency(%q<tagged_logger>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 0"])
  end
end

